refactoring and new functions

diff --git a/deploy b/deploy
--- a/deploy
+++ b/deploy
@@ -1,2 +1,8 @@
 #!/bin/bash
-cp ./* /Users/leonmax/Library/Application Support/technic/modpacks/tekkitmain/saves/Badass/computer/19/
+if [ -z "$1" ]
+then
+  echo "computer id can't be empty"
+  exit 1
+fi
+mkdir -pv /Users/leonmax/Library/Application\ Support/technic/modpacks/tekkitmain/saves/Badass/computer/$1
+cp -rv ./* /Users/leonmax/Library/Application\ Support/technic/modpacks/tekkitmain/saves/Badass/computer/$1/
